### PR TITLE
Tweak the default scaffolding to add auth files

### PR DESCRIPTION
**Pull request by tonysm**
### Added

- Adds the auth files (Vue Pages)
- Adds the provider to bind some variables to all pages (copied from the PingCRM)
- Adds instructions to generate the auth scaffolding

### CODE REVIEW

**Comment by tonysm** [comment]
Not sure you are interested in something like this. I took the time to implement the auth scaffoldings in Inertia.js as well, took some inspirations from the [PingCRM](https://github.com/inertiajs/pingcrm) project.

Found this useful to me, but it's ok if you think it's not suited for the preset (as there are some assumptions in the created components, like the FormInput, FlashMessages, and stuff).

I can always make my own preset. ;)

**Comment by reinink** [comment]
Yeah this is certainly neat, and definitely helpful in some situations. I do worry it's "too much". I'd rather have the Inertia preset be a simple as possible.

I personally never use presets. Is there a way to specify options when using a preset? For example, maybe by default it doesn't include the auth stuff, but you could pass a flag to enable it?

My fear is that this can quickly turn into a big thing to maintain.

@michaeldyrynda What do you think?

**Comment by tonysm** [comment]
@reinink that's already how this PR is working.

The default preset only creates 2 page components (before it was 3):

```bash
php artisan preset inertiajs
```

and if you want the scaffolding, you can do:

```bash
php artisan preset inertiajs --option=auth
```

it felt too much when I was adding these stuff idd, but I find the auth scaffolding really helpful (like that's literally the first thing I do in a new laravel app).

**Comment by tonysm** [comment]
Closing this, feels like too many opinions for a preset. ;)

**Pull request closed without merging**
